### ISSUE TITLE
No attached license

### ISSUE THREAD

**Issue by bfrymire** [Limekys/AdvancedParticleSystem#5]
Hello, it's best to attach a license to your library so other may know how they can use it.

I've linked some reading below to help guide you on which license to choose.

The Legal Side of Open Source:
https://opensource.guide/legal/

Common Licenses:
https://choosealicense.com/licenses/

GitHub Adding a License to a Repository:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by bfrymire** [comment]
May I suggest the MIT License:

https://choosealicense.com/licenses/mit/

**Comment by Limekys** [comment]
Added, thanks for the remark!
